- name: Crear contenidor Docker amb Postfix
  hosts: servidores
  become: true
  tasks:

    - name: Crear carpeta del Dockerfile
      file:
        path: /opt/postfix-container
        state: directory
        mode: '0755'

    - name: Crear subcarpeta per al fitxer /etc/mailname
      file:
        path: /opt/postfix-container/etc
        state: directory
        mode: '0755'

    - name: Crear fitxer /etc/mailname
      copy:
        dest: /opt/postfix-container/etc/mailname
        content: "elpuig.example.com\n"
        mode: '0644'

    - name: Crear Dockerfile de Postfix
      copy:
        dest: /opt/postfix-container/Dockerfile
        content: |
          FROM debian:bookworm
          ENV DEBIAN_FRONTEND=noninteractive
          COPY etc/mailname /etc/mailname
          RUN apt update && apt install -y postfix && \
              sed -i 's/^#myhostname =.*/myhostname = elpuig.example.com/' /etc/postfix/main.cf && \
              sed -i 's/^#mydestination =.*/mydestination = $myhostname, localhost.localdomain, localhost/' /etc/postfix/main.cf
          EXPOSE 25
          CMD ["sh", "-c", "service postfix start && tail -f /dev/null"]

    - name: Construir imatge Docker de Postfix
      community.docker.docker_image:
        name: postfix-image
        source: build
        build:
          path: /opt/postfix-container

    - name: Assegurar que el contenidor està corrent
      community.docker.docker_container:
        name: postfix-container
        image: postfix-image
        state: started
        restart_policy: always
        published_ports:
          - "2525:25"
