- name: Crear contenidor Docker amb Postfix relay intern
  hosts: servidores
  become: true

  tasks:
    - name: Crear carpeta /opt/postfix-intern/etc
      file:
        path: /opt/postfix-intern/etc
        state: directory
        mode: '0755'

    - name: Crear fitxer /etc/mailname
      copy:
        dest: /opt/postfix-intern/etc/mailname
        content: "elpuig.example.com\n"
        mode: '0644'

    - name: Crear fitxer main.cf per relay intern
      copy:
        dest: /opt/postfix-intern/etc/main.cf
        content: |
          myhostname = elpuig.example.com
          mydestination = $myhostname, localhost.localdomain, localhost
          relayhost =
          inet_interfaces = all
          smtpd_banner = $myhostname ESMTP
          biff = no
          append_dot_mydomain = no
          readme_directory = no
          smtp_tls_security_level = may
          smtpd_tls_security_level = may
        mode: '0644'

    - name: Crear Dockerfile per Postfix bàsic
      copy:
        dest: /opt/postfix-intern/Dockerfile
        content: |
          FROM debian:bookworm
          ENV DEBIAN_FRONTEND=noninteractive
          COPY etc/main.cf /etc/postfix/main.cf
          COPY etc/mailname /etc/mailname
          RUN apt update && apt install -y postfix bsd-mailx
          EXPOSE 25
          CMD ["postfix", "start-fg"]

    - name: Construir imatge Docker de Postfix bàsic
      community.docker.docker_image:
        name: postfix-intern-image
        source: build
        build:
          path: /opt/postfix-intern

    - name: Llançar contenidor Postfix intern
      community.docker.docker_container:
        name: postfix-intern-container
        image: postfix-intern-image
        state: started
        restart_policy: always
        published_ports:
          - "2525:25"
        dns_servers:
          - "8.8.8.8"
          - "8.8.4.4"
