- name: Instal·lar Docker a sistemes Debian/Ubuntu
  hosts: servidores
  become: true

  tasks:
    - name: Actualitzar la caché de paquets APT
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Instal·lar dependències necessàries
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg
          - lsb-release
        state: present

    - name: Afegir clau GPG oficial de Docker
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Afegir repositori oficial de Docker
      apt_repository:
        repo: deb [arch=amd64] https://download.docker.com/linux/ubuntu {{ ansible_lsb.codename }} stable
        state: present

    - name: Actualitzar la caché de paquets amb el nou repositori
      apt:
        update_cache: yes
        force_apt_get: yes

    - name: Instal·lar Docker Engine
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: latest

    - name: Afegir usuari actual al grup docker
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    - name: Assegurar que el servei de Docker està actiu
      service:
        name: docker
        state: started
        enabled: yes
