- name: Llançar contenidor Duplicati
  hosts: servidores
  become: true
  vars:
    duplicati_version: "linuxserver/duplicati:latest"
    duplicati_password: "zafrazafra13"

  tasks:
    - name: Crear directori per a Duplicati
      file:
        path: /opt/duplicati
        state: directory
        mode: '0755'

    - name: Llançar contenidor Duplicati
      community.docker.docker_container:
        name: duplicati
        image: "{{ duplicati_version }}"
        state: started
        restart_policy: always
        published_ports:
          - "8200:8200"
        env:
          PUID: "1000"
          PGID: "1000"
          TZ: "Europe/Madrid"
          SETTINGS_ENCRYPTION_KEY: "clau-super-secreta-123"
          DUPLICATI_PASS: "{{ duplicati_password }}"
          DUPLICATI__WEBSERVICE_PASSWORD: "admin"
        volumes:
          - /opt/duplicati/config:/config
          - /opt/duplicati/backups:/backups
          - /opt/duplicati/source:/source
