- name: Crear y lanzar relanzar.sh en segundo plano
  hosts: servidores
  become: true
  vars:
    base_path: /home/usuario/projecte-asix
    script_path: /home/usuario/projecte-asix/relanzar.sh

  tasks:
    - name: Crear script relanzar.sh
      copy:
        dest: "{{ script_path }}"
        mode: '0755'
        content: |
          #!/bin/bash
          BASE_PATH="{{ base_path }}"
          echo "$(date): relanzar.sh ejecutado" >> "$BASE_PATH/debug.log"

          check_container() {
              CONTAINER_NAME=$1
              PLAYBOOK_PATH=$2
              STATUS=$(docker inspect -f '{{"{{"}}.State.Running{{"}}"}}' "$CONTAINER_NAME" 2>/dev/null)
              if [ $? -ne 0 ]; then
                  echo "$(date): ❌ Contenedor '$CONTAINER_NAME' no existe." >> "$BASE_PATH/monitor.log"
                  return
              fi
              if [ "$STATUS" != "true" ]; then
                  echo "$(date): ⚠️  $CONTAINER_NAME está caído. Reiniciando con Ansible..." >> "$BASE_PATH/monitor.log"
                  ansible-playbook -i "$BASE_PATH/inventory.ini" "$PLAYBOOK_PATH" >> "$BASE_PATH/monitor.log" 2>&1
              else
                  echo "$(date): ✅ $CONTAINER_NAME está funcionando correctamente." >> "$BASE_PATH/monitor.log"
              fi
          }

          check_container "grafana" "$BASE_PATH/monitorizatge3000/monitorizar.yml.yml"
          check_container "cadvisor" "$BASE_PATH/monitorizatge3000/monitorizar.yml.yml"
          check_container "prometheus" "$BASE_PATH/monitorizatge3000/monitorizar.yml"
          check_container "postfix-intern-container" "$BASE_PATH/postfix/contenidor-postfix.yml"
          check_container "filebrowser" "$BASE_PATH/monitorizatge3000/contenidor-filebrowser.yml"
          check_container "ftp-server" "$BASE_PATH/ftp8081/contenidor-ftp.yml"
          check_container "apache_final" "$BASE_PATH/apache8080/crear-contenedor-apache.yml"
          check_container "postgres" "$BASE_PATH/bbdd/contenidor-postgres.yml"

    - name: Lanzar relanzar.sh en segundo plano con nohup (si no está corriendo)
      shell: |
        if ! pgrep -f "relanzar.sh" > /dev/null; then
          nohup {{ script_path }} >> {{ base_path }}/monitor.log 2>&1 &
        fi
      args:
        executable: /bin/bash
