- name: Crear contenedor Docker amb Apache i SSH
  hosts: servidores
  become: true
  tasks:

    - name: Crear carpeta del Dockerfile
      file:
        path: /opt/apache-ssh
        state: directory

    - name: Copiar Dockerfile
      copy:
        dest: /opt/apache-ssh/Dockerfile
        content: |
          FROM debian:bookworm
          ENV DEBIAN_FRONTEND=noninteractive
          RUN apt update && apt install -y apache2 openssh-server && \
              mkdir /var/run/sshd && \
              echo "root:root" | chpasswd && \
              sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config && \
              sed -i 's/#PasswordAuthentication yes/PasswordAuthentication yes/' /etc/ssh/sshd_config && \
              echo 'ServerName localhost' >> /etc/apache2/apache2.conf
          EXPOSE 80 22
          CMD service apache2 start && /usr/sbin/sshd -D

    - name: Construir imatge Docker
      community.docker.docker_image:
        name: apache-ssh
        source: build   # <-- Esto es lo que te faltaba
        build:
          path: /opt/apache-ssh

    - name: Assegurar que el contenidor està corrent
      community.docker.docker_container:
        name: apache_final
        image: apache-ssh
        state: started
        restart_policy: always
        published_ports:
          - "8080:80"
          - "2222:22"
