- name: Injectar index.html dins del contenidor Apache
  hosts: servidores
  become: yes
  tasks:
    - name: Crear directori dins el contenidor si no existeix
      command: docker exec apache_final mkdir -p /usr/local/apache2/htdocs

    - name: Copiar index.html al contenidor apache_final
      command: docker cp /tmp/index.html apache_final:/var/www/html/index.html

    - name: Reiniciar Apache dins del contenidor
      command: docker exec apache_final service apache2 restart
